name: TestsPipeline
on:
  push:
    branches:
      - 'experiment/**'
  pull_request:
    branches:
      - main
concurrency:
  group: TestsPipeline
  cancel-in-progress: true
jobs:

  ubuntu-test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        java: [ '11' ]
    name: ${{ matrix.platform }} - Java ${{ matrix.Java }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}
      - name: Install Chrome and MSEdge
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chrome msedge"
      - name: Install deps
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"
      - name: Run Tests
        run: mvn test
      - name: jUnit Test Result for - ${{ matrix.platform }} - Java ${{ matrix.Java }}
        uses: mikepenz/action-junit-report@v2
        if: failure()
        with:
          report_paths: target/surefire-reports/*.xml

  macosx-test:
    strategy:
      matrix:
        platform: [ macos-latest ]
        java: [ '11' ]
    name: ${{ matrix.platform }} - Java ${{ matrix.Java }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}
      - name: Install Chrome and MSEdge
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chrome msedge"
      - name: Install deps
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"
      - name: Run Tests
        run: mvn test
      - name: jUnit Test Result for - ${{ matrix.platform }} - Java ${{ matrix.Java }}
        uses: mikepenz/action-junit-report@v2
        if: failure()
        with:
          report_paths: target/surefire-reports/*.xml

  windows-test:
    strategy:
      matrix:
        platform: [ windows-latest ]
        java: [ '11' ]
    name: ${{ matrix.platform }} - Java ${{ matrix.Java }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}
      - name: Run Tests
        run: mvn test
      - name: jUnit Test Result for - ${{ matrix.platform }} - Java ${{ matrix.Java }}
        uses: mikepenz/action-junit-report@v2
        if: failure()
        with:
          report_paths: target/surefire-reports/*.xml
