name: TestsPipeline
on:
  push:
    branches:
      - 'experiment/**'
  pull_request:
    branches:
      - main
concurrency:
  group: TestsPipeline
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        java: [ '8', '11', '17' ]
    name: ${{ matrix.platform }} - Java ${{ matrix.Java }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.Java }}
      - name: Install Chrome and MSEdge
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chrome msedge"
      - name: Install deps
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"
      - name: Run Tests
        run: mvn test
